#!/bin/python3

from urllib.parse import quote
from pandocfilters import toJSONFilter, RawInline
from pkg_resources import resource_filename

from gcd.nix import sh, sh_quote, path, os, cmd, env, sys


def codecogs(key, value, format, meta):
    if key == 'Math':
        inline = value[0]['t'] == 'InlineMath'
        latex = '\\inline ' + value[1] if inline else value[1]
        url = 'http://latex.codecogs.com/gif.latex?' + quote(latex)
        if format.startswith('markdown'):
            return RawInline('markdown', '![](%s)' % url)
        elif format == 'html':
            return RawInline('html', '<img src="%s"></img>' % url)


def tmpout(args):
    output_dir = '/tmp/liftup'
    output_name = path.splitext(
        path.abspath(args.input).replace('/', '$'))[0]
    output_ext = 'pdf' if args.type == 'pdf' else 'html'
    if not path.exists(output_dir):
        os.mkdir(output_dir)
    return '%s/%s.%s' % (output_dir, output_name, output_ext)


@cmd.run
def main():
    """Convert any input supported by pandoc to html (page or snippet), pdf
    (via pdflatex) or github flavored markdown (aka gfm). Include formulas as
    mathjax or codecogs urls.
    """

    if '_CODECOGS' in env:
        toJSONFilter(codecogs)
        sys.exit(0)

    cmd.arg('--output', '-o',
            help="""Output file, by default a temporary file uniquely
                 associated with the input file.""")
    cmd.arg('--type', '-t', default='html',
            choices=['html', 'pdf', 'gfm', 'snippet'],
            help='Output type, by default html.')
    cmd.arg('--mathimg', '-m', action='store_true',
            help='Render math as image url. Always true for -t gfm.')
    cmd.arg('--subst', '-s', action='store_true',
            help="""Prints the output path to stdout in order to facilitate
                 command substitution.""")
    cmd.arg('input')
    args = cmd.args

    output = args.output if args.output else tmpout(args)
    pandoc = 'pandoc -S -c %s -o %s' % (
        sh_quote(resource_filename('gcd', 'resources/github.css')),
        sh_quote(output))

    if args.type == 'snippet':
        pandoc += ' -t html --template=' + sh_quote(
            resource_filename('gcd', 'resources/snippet.html'))
    elif args.type == 'gfm':
        pandoc += ' -s -t markdown_github'
        args.mathimg = True
    else:
        pandoc += ' -s -t ' + ('latex' if args.type == 'pdf' else 'html')

    if args.mathimg:
        pandoc = '_CODECOGS=1 ' + pandoc + ' --filter liftup'
    else:
        pandoc += ' --mathjax'

    if args.input.endswith('.md'):
        extensions = '+lists_without_preceding_blankline+autolink_bare_uris'
        pandoc += ' -f markdown' + extensions

    sh(pandoc + ' ' + sh_quote(args.input))

    if args.subst:
        print(output)
